// Generated by Wrangler by running `wrangler types`

interface Env {
	ENV: "development" | "production";
	ALLOWED_ORIGINS: ["http://localhost:3000", "http://localhost:5500", "http://127.0.0.1:5500"];
	ACCESS_TOKEN_SECRET: string;
	REFRESH_TOKEN_SECRET: string;
	ACCESS_TOKEN_EXPIRY: string;
	REFRESH_TOKEN_EXPIRY: string;
	ACCESS_TOKEN_COOKIE_NAME: string;
	REFRESH_TOKEN_COOKIE_NAME: string;
	DB: D1Database;
}
