GET http://localhost:8787/health

###
# @name login
POST http://localhost:8787/api/v1/auth/login
Content-Type: application/json

{
  "email": "Eldora.Crooks38@hotmail.com",
  "password": "this-is-a-very-secure-password"
}

###

GET http://localhost:8787/health

###
@authToken = {{login.response.headers.Set-Cookie[0]}}
@pippo = {{authToken.split(';')[0]}}

# @name loginResponse
GET http://localhost:8787/api/v1/users/me
Authorization: Bearer {{authToken}}

###
GET http://localhost:8787/api/v1/users/me

###
curl --request POST \
  --url http://localhost:8787/api/v1/auth/login \
  --header 'Content-Type: application/json' \
  --header 'User-Agent: insomnia/10.3.1' \
  --data '{
  "email" : "Eldora.Crooks38@hotmail.com" ,
  "password": "this-is-a-very-secure-password"
}' \
  --cookie cookies.txt \
  --cookie-jar cookies.txt
